### ISSUE TITLE
Running examples/configuration not hot reloading

### ISSUE THREAD

**Issue by idkjs** [c8r/x0#45]
yarn install then yarn start load the project in the browser.

making an edit to App.js recompiles webpack but doesnt reload in Firefox

- yarn error Trace:

```log
Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c x0 dev App.js -o
  Directory: /Users/prisc_000/code/BHYV/x0/examples/configuration
  Output:
  
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:160:13)
      at maybeClose (internal/child_process.js:943:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

If you run `yarn build` it kinda just doesnt ever finish:
[![https://gyazo.com/f6feb00e9c6d852c419227b905092bcc](https://i.gyazo.com/f6feb00e9c6d852c419227b905092bcc.gif)](https://gyazo.com/f6feb00e9c6d852c419227b905092bcc)

If you refresh the browser, you get this:

![screenshot](https://user-images.githubusercontent.com/2370391/37121657-31b8ad58-225e-11e8-9ff5-13616e795559.png)

**Comment by johno** [comment]
This should now be fixed with v5. Please let us know if that isn't the case.

**Comment by idkjs** [comment]
Confirmed.

<img width="724" alt="screen shot 2018-05-29 at 10 41 40 am" src="https://user-images.githubusercontent.com/2370391/40647765-ff5ff6bc-632c-11e8-935b-363fc36593d5.png">


Thank you for taking the time to respond.

Keep up the great work!

Peace to you.
